/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/RM5av09vI6M
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import { AvatarImage, Avatar } from "@/components/ui/avatar"
import { Button } from "@/components/ui/button"
import { CardContent, Card } from "@/components/ui/card"

export function AppDirectory() {
  return (
    <div key="1" className="flex h-screen bg-[#ffcc00]">
      <div className="w-1/5 p-4 bg-[#B8DFD9]">
        <div className="flex items-center space-x-4 mb-8">
          <Avatar>
            <AvatarImage alt="School Logo" src="/placeholder.svg?height=50&width=50" />
          </Avatar>
          <span className="text-2xl font-bold text-white">myDay</span>
        </div>
        <nav className="space-y-2">
          <Button className="w-full bg-[#F49812] text-black">
            <HomeIcon className="mr-2 h-4 w-4" />
            Home
          </Button>
          <Button className="w-full bg-[#F49812] text-black">
            <LibraryIcon className="mr-2 h-4 w-4" />
            Library
          </Button>
          <Button className="w-full bg-[#F49812] text-black">
            <TrophyIcon className="mr-2 h-4 w-4" />
            Sport
          </Button>
          <Button className="w-full bg-[#F49812] text-black">
            <ShieldIcon className="mr-2 h-4 w-4" />
            Safeguarding
          </Button>
          <Button className="w-full bg-[#F49812] text-black">
            <BookIcon className="mr-2 h-4 w-4" />
            Academic
          </Button>
        </nav>
        <div className="absolute bottom-4 left-4 flex items-center space-x-2">
          <Avatar>
            <AvatarImage alt="User" src="/placeholder.svg?height=40&width=40" />
          </Avatar>
          <span className="text-lg font-bold text-white">Leo Wilkin</span>
          <ChevronRightIcon className="text-white h-6 w-6" />
        </div>
      </div>
      <div className="w-3/4 p-8 space-y-4">
        <div className="grid grid-cols-3 gap-4">
          <Card className="w-full bg-[#ffe680]">
            <CardContent className="flex items-center justify-center space-x-2">
              <CloudIcon className="text-black h-6 w-6" />
              <span className="text-lg font-bold text-black">OneDrive</span>
            </CardContent>
          </Card>
          <Card className="w-full bg-[#ffe680]">
            <CardContent className="flex items-center justify-center space-x-2">
              <GlobeIcon className="text-black h-6 w-6" />
              <span className="text-lg font-bold text-black">Planet eStream</span>
            </CardContent>
          </Card>
          <Card className="w-full bg-[#ffe680]">
            <CardContent className="flex items-center justify-center space-x-2">
              <ShareIcon className="text-black h-6 w-6" />
              <span className="text-lg font-bold text-black">Sharepoint</span>
            </CardContent>
          </Card>
          <Card className="w-full bg-[#ffe680]">
            <CardContent className="flex items-center justify-center space-x-2">
              <MailboxIcon className="text-black h-6 w-6" />
              <span className="text-lg font-bold text-black">Outlook</span>
            </CardContent>
          </Card>
          <Card className="w-full bg-[#ffe680]" />
          <Card className="w-full bg-[#ffe680]" />
        </div>
      </div>
    </div>
  )
}

function BookIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M4 19.5v-15A2.5 2.5 0 0 1 6.5 2H20v20H6.5a2.5 2.5 0 0 1 0-5H20" />
    </svg>
  )
}


function ChevronRightIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m9 18 6-6-6-6" />
    </svg>
  )
}


function CloudIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M17.5 19H9a7 7 0 1 1 6.71-9h1.79a4.5 4.5 0 1 1 0 9Z" />
    </svg>
  )
}


function GlobeIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="10" />
      <line x1="2" x2="22" y1="12" y2="12" />
      <path d="M12 2a15.3 15.3 0 0 1 4 10 15.3 15.3 0 0 1-4 10 15.3 15.3 0 0 1-4-10 15.3 15.3 0 0 1 4-10z" />
    </svg>
  )
}


function HomeIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m3 9 9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z" />
      <polyline points="9 22 9 12 15 12 15 22" />
    </svg>
  )
}


function LibraryIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m16 6 4 14" />
      <path d="M12 6v14" />
      <path d="M8 8v12" />
      <path d="M4 4v16" />
    </svg>
  )
}


function MailboxIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M22 17a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V9.5C2 7 4 5 6.5 5H18c2.2 0 4 1.8 4 4v8Z" />
      <polyline points="15,9 18,9 18,11" />
      <path d="M6.5 5C9 5 11 7 11 9.5V17a2 2 0 0 1-2 2v0" />
      <line x1="6" x2="7" y1="10" y2="10" />
    </svg>
  )
}


function ShareIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M4 12v8a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2v-8" />
      <polyline points="16 6 12 2 8 6" />
      <line x1="12" x2="12" y1="2" y2="15" />
    </svg>
  )
}


function ShieldIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10" />
    </svg>
  )
}


function TrophyIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M6 9H4.5a2.5 2.5 0 0 1 0-5H6" />
      <path d="M18 9h1.5a2.5 2.5 0 0 0 0-5H18" />
      <path d="M4 22h16" />
      <path d="M10 14.66V17c0 .55-.47.98-.97 1.21C7.85 18.75 7 20.24 7 22" />
      <path d="M14 14.66V17c0 .55.47.98.97 1.21C16.15 18.75 17 20.24 17 22" />
      <path d="M18 2H6v7a6 6 0 0 0 12 0V2Z" />
    </svg>
  )
}
